### ISSUE TITLE
[Feature Request] Tags Colours suggestions

### ISSUE THREAD

**Issue by sakkamade** [leoding86/pixiv-omina#75]
### Omina Version and Operating System
4c9a969f7882f55668e65f5381cbf7bd795a207c, and Arch Linux

### What is the request
I should like to suggest some changes in tags' colours.
<details><summary>Screenshots (click here)</summary>

#### `0.8.0`, 4c9a969f7882f55668e65f5381cbf7bd795a207c, novels (hardly readable)
![pix novel](https://user-images.githubusercontent.com/62730422/123037464-3f1d0900-d3de-11eb-92ea-0e91e44e10f0.png)
#### `0.7.7`, 9ece03759bfcde4c0f1929e65d2bf633ed73870b, not-yet-started item
![pix undetermined 0 7 7](https://user-images.githubusercontent.com/62730422/123037466-3fb59f80-d3de-11eb-844c-efeb08f6cfda.png)
#### `0.8.0`, 4c9a969f7882f55668e65f5381cbf7bd795a207c, not-yet-started item
![pix undetermined 0 8](https://user-images.githubusercontent.com/62730422/123037467-3fb59f80-d3de-11eb-8798-461c1da2bd7c.png)

</details>

Thus, I would like to see all "not-yet-started" items (such as Pixiv Artwork) how they used to be, in some `rgb(152, 152, 152)`, so to not attract much attention, and novels in slightly darker than current `rgb(195, 195, 195)`, or blue `rgb(55, 155, 255)` or `rgb(75, 165, 255)`.

**Comment by leoding86** [comment]
Add theme support. You can create a `theme.css` file in application's `config` folder and customize UI. For customize tag colors, you can overwrite class and reload theme in general setting.

Default color style:

```scss
.download-list-item--undetermined {
  .download-list-item-item__tag {
    background: rgb(125, 125, 125);
  }
}

.download-list-item--pixiv_ugoira {
  .download-list-item__tag {
    background: rgb(255, 170, 139);
  }
}

.download-list-item--pixiv_illustration {
  .download-list-item__tag {
    background: rgb(226, 118, 118);
  }
}

.download-list-item--pixiv_manga {
  .download-list-item__tag {
    background: rgb(146, 215, 218);
  }
}

.download-list-item--pixiv_comic {
  .download-list-item__tag {
    background: rgb(0, 135, 255);
  }
}

.download-list-item--pixiv_novel {
  .download-list-item__tag {
    background: rgb(55, 55, 55);
  }
}
```
